#!/bin/sh
### BEGIN INIT INFO
# Provides:          iotcoredemo
# Required-Start:    $network $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: iotcore demo app
# Description:       iotcore demo app
### END INIT INFO

DESC="IoT Core Config Service"
NAME=iotcoredemo
PNAME=iotcoredemo
DIR=/opt/iotcore-raspbian-demo/
DAEMON=`which node`
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$PNAME
LOGFILE=/var/log/iotcoredemo/iot.log

do_start()
{
  echo "Starting $DESC at `date`" >> $LOGFILE
  start-stop-daemon --start --background --no-close --verbose --pidfile $PIDFILE -m --user pi --chuid pi --chdir $DIR --startas $DAEMON -- main.js >> $LOGFILE 2>&1
  RETVAL="$?"
  return "$RETVAL"
}

do_stop()
{
  echo "Stopping $DESC at `date`" >> $LOGFILE
  start-stop-daemon --stop --pidfile $PIDFILE --remove-pidfile
  RETVAL="$?"
  return "$RETVAL"
}

case "$1" in
  start)
    echo "Starting $DESC"
    do_start
  ;;
  stop)
    echo "Stopping $DESC"
    do_stop
  ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop}" >&2
    exit 3
  ;;
esac
